/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BlockedSlot = IDL.Record({
  'date' : IDL.Int,
  'reason' : IDL.Text,
  'startHour' : IDL.Int,
});
export const TimeSlot = IDL.Record({
  'duration' : IDL.Int,
  'date' : IDL.Int,
  'startHour' : IDL.Int,
});
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'bookedBy' : IDL.Principal,
  'sport' : IDL.Text,
  'timestamp' : IDL.Int,
  'phoneNumber' : IDL.Text,
  'price' : IDL.Int,
  'timeSlot' : TimeSlot,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const EarningsReport = IDL.Record({
  'endDate' : IDL.Int,
  'totalRevenue' : IDL.Nat,
  'bookingCount' : IDL.Nat,
  'startDate' : IDL.Int,
});
export const PricingRules = IDL.Record({
  'weekdayFloodlightRate' : IDL.Int,
  'floodlightStartHour' : IDL.Int,
  'weekendFloodlightRate' : IDL.Int,
  'weekendMorningRate' : IDL.Int,
  'weekdayMorningRate' : IDL.Int,
});
export const SlotSettings = IDL.Record({
  'openingTime' : IDL.Int,
  'closingTime' : IDL.Int,
  'slotDuration' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOwner' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockSlot' : IDL.Func([BlockedSlot], [], []),
  'book' : IDL.Func([TimeSlot, IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'checkAvailability' : IDL.Func([IDL.Int], [IDL.Vec(IDL.Int)], ['query']),
  'claimNewOwnership' : IDL.Func([], [], []),
  'clearExplicitRoles' : IDL.Func([], [], []),
  'emergencyResetOwnership' : IDL.Func([IDL.Text], [], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], []),
  'getBlockedSlots' : IDL.Func([], [IDL.Vec(BlockedSlot)], ['query']),
  'getBooking' : IDL.Func([IDL.Text], [Booking], ['query']),
  'getBookingsCount' : IDL.Func([], [IDL.Nat], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyEarnings' : IDL.Func([IDL.Int], [EarningsReport], []),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getOwners' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getPricingRules' : IDL.Func([], [PricingRules], ['query']),
  'getSlotSettings' : IDL.Func([], [SlotSettings], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeeklyEarnings' : IDL.Func([IDL.Int, IDL.Int], [EarningsReport], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isOwner' : IDL.Func([], [IDL.Bool], ['query']),
  'isOwnershipClaimable' : IDL.Func([], [IDL.Bool], ['query']),
  'postMigrationClearExplicitRoles' : IDL.Func([], [], []),
  'removeOwner' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unblockSlot' : IDL.Func([IDL.Int, IDL.Int], [], []),
  'updatePricingRules' : IDL.Func([PricingRules], [], []),
  'updateSlotSettings' : IDL.Func([SlotSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BlockedSlot = IDL.Record({
    'date' : IDL.Int,
    'reason' : IDL.Text,
    'startHour' : IDL.Int,
  });
  const TimeSlot = IDL.Record({
    'duration' : IDL.Int,
    'date' : IDL.Int,
    'startHour' : IDL.Int,
  });
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'bookedBy' : IDL.Principal,
    'sport' : IDL.Text,
    'timestamp' : IDL.Int,
    'phoneNumber' : IDL.Text,
    'price' : IDL.Int,
    'timeSlot' : TimeSlot,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const EarningsReport = IDL.Record({
    'endDate' : IDL.Int,
    'totalRevenue' : IDL.Nat,
    'bookingCount' : IDL.Nat,
    'startDate' : IDL.Int,
  });
  const PricingRules = IDL.Record({
    'weekdayFloodlightRate' : IDL.Int,
    'floodlightStartHour' : IDL.Int,
    'weekendFloodlightRate' : IDL.Int,
    'weekendMorningRate' : IDL.Int,
    'weekdayMorningRate' : IDL.Int,
  });
  const SlotSettings = IDL.Record({
    'openingTime' : IDL.Int,
    'closingTime' : IDL.Int,
    'slotDuration' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOwner' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockSlot' : IDL.Func([BlockedSlot], [], []),
    'book' : IDL.Func([TimeSlot, IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'checkAvailability' : IDL.Func([IDL.Int], [IDL.Vec(IDL.Int)], ['query']),
    'claimNewOwnership' : IDL.Func([], [], []),
    'clearExplicitRoles' : IDL.Func([], [], []),
    'emergencyResetOwnership' : IDL.Func([IDL.Text], [], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], []),
    'getBlockedSlots' : IDL.Func([], [IDL.Vec(BlockedSlot)], ['query']),
    'getBooking' : IDL.Func([IDL.Text], [Booking], ['query']),
    'getBookingsCount' : IDL.Func([], [IDL.Nat], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyEarnings' : IDL.Func([IDL.Int], [EarningsReport], []),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getOwners' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getPricingRules' : IDL.Func([], [PricingRules], ['query']),
    'getSlotSettings' : IDL.Func([], [SlotSettings], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeeklyEarnings' : IDL.Func([IDL.Int, IDL.Int], [EarningsReport], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isOwner' : IDL.Func([], [IDL.Bool], ['query']),
    'isOwnershipClaimable' : IDL.Func([], [IDL.Bool], ['query']),
    'postMigrationClearExplicitRoles' : IDL.Func([], [], []),
    'removeOwner' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unblockSlot' : IDL.Func([IDL.Int, IDL.Int], [], []),
    'updatePricingRules' : IDL.Func([PricingRules], [], []),
    'updateSlotSettings' : IDL.Func([SlotSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };