/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlockedSlot {
  'date' : bigint,
  'reason' : string,
  'startHour' : bigint,
}
export interface Booking {
  'id' : string,
  'customerName' : string,
  'bookedBy' : Principal,
  'sport' : string,
  'timestamp' : bigint,
  'phoneNumber' : string,
  'price' : bigint,
  'timeSlot' : TimeSlot,
}
export interface EarningsReport {
  'endDate' : bigint,
  'totalRevenue' : bigint,
  'bookingCount' : bigint,
  'startDate' : bigint,
}
export interface PricingRules {
  'weekdayFloodlightRate' : bigint,
  'floodlightStartHour' : bigint,
  'weekendFloodlightRate' : bigint,
  'weekendMorningRate' : bigint,
  'weekdayMorningRate' : bigint,
}
export interface SlotSettings {
  'openingTime' : bigint,
  'closingTime' : bigint,
  'slotDuration' : bigint,
}
export interface TimeSlot {
  'duration' : bigint,
  'date' : bigint,
  'startHour' : bigint,
}
export interface UserProfile { 'name' : string, 'phoneNumber' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockSlot' : ActorMethod<[BlockedSlot], undefined>,
  'book' : ActorMethod<[TimeSlot, string, string, string], string>,
  'checkAvailability' : ActorMethod<[bigint], Array<bigint>>,
  'claimNewOwnership' : ActorMethod<[], undefined>,
  'clearExplicitRoles' : ActorMethod<[], undefined>,
  'emergencyResetOwnership' : ActorMethod<[string], undefined>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getBlockedSlots' : ActorMethod<[], Array<BlockedSlot>>,
  'getBooking' : ActorMethod<[string], Booking>,
  'getBookingsCount' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyEarnings' : ActorMethod<[bigint], EarningsReport>,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getPricingRules' : ActorMethod<[], PricingRules>,
  'getSlotSettings' : ActorMethod<[], SlotSettings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeeklyEarnings' : ActorMethod<[bigint, bigint], EarningsReport>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isOwnershipClaimable' : ActorMethod<[], boolean>,
  'postMigrationClearExplicitRoles' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unblockSlot' : ActorMethod<[bigint, bigint], undefined>,
  'updatePricingRules' : ActorMethod<[PricingRules], undefined>,
  'updateSlotSettings' : ActorMethod<[SlotSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];