/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TimeSlot {
    duration: bigint;
    date: bigint;
    startHour: bigint;
}
export interface PricingRules {
    weekdayFloodlightRate: bigint;
    floodlightStartHour: bigint;
    weekendFloodlightRate: bigint;
    weekendMorningRate: bigint;
    weekdayMorningRate: bigint;
}
export interface SlotSettings {
    openingTime: bigint;
    closingTime: bigint;
    slotDuration: bigint;
}
export interface EarningsReport {
    endDate: bigint;
    totalRevenue: bigint;
    bookingCount: bigint;
    startDate: bigint;
}
export interface Booking {
    id: string;
    customerName: string;
    bookedBy: Principal;
    sport: string;
    timestamp: bigint;
    phoneNumber: string;
    price: bigint;
    timeSlot: TimeSlot;
}
export interface BlockedSlot {
    date: bigint;
    reason: string;
    startHour: bigint;
}
export interface UserProfile {
    name: string;
    phoneNumber: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    backendResetAndClaimOwnership(): Promise<void>;
    blockSlot(slot: BlockedSlot): Promise<void>;
    book(timeSlot: TimeSlot, customerName: string, phoneNumber: string, sport: string): Promise<string>;
    checkAvailability(date: bigint): Promise<Array<bigint>>;
    emergencyResetOwnership(authorizationKey: string): Promise<void>;
    getAllBookings(): Promise<Array<Booking>>;
    getBlockedSlots(): Promise<Array<BlockedSlot>>;
    getBooking(id: string): Promise<Booking>;
    getBookingsCount(): Promise<bigint>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDailyEarnings(date: bigint): Promise<EarningsReport>;
    getMyBookings(): Promise<Array<Booking>>;
    getPricingRules(): Promise<PricingRules>;
    getSlotSettings(): Promise<SlotSettings>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWeeklyEarnings(startDate: bigint, endDate: bigint): Promise<EarningsReport>;
    isCallerAdmin(): Promise<boolean>;
    isOwnershipClaimable(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    unblockSlot(date: bigint, startHour: bigint): Promise<void>;
    updatePricingRules(rules: PricingRules): Promise<void>;
    updateSlotSettings(settings: SlotSettings): Promise<void>;
}
import type { UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async backendResetAndClaimOwnership(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.backendResetAndClaimOwnership();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.backendResetAndClaimOwnership();
            return result;
        }
    }
    async blockSlot(arg0: BlockedSlot): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockSlot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockSlot(arg0);
            return result;
        }
    }
    async book(arg0: TimeSlot, arg1: string, arg2: string, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.book(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.book(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async checkAvailability(arg0: bigint): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.checkAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkAvailability(arg0);
            return result;
        }
    }
    async emergencyResetOwnership(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.emergencyResetOwnership(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.emergencyResetOwnership(arg0);
            return result;
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return result;
        }
    }
    async getBlockedSlots(): Promise<Array<BlockedSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlockedSlots();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlockedSlots();
            return result;
        }
    }
    async getBooking(arg0: string): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return result;
        }
    }
    async getBookingsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsCount();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyEarnings(arg0: bigint): Promise<EarningsReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyEarnings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyEarnings(arg0);
            return result;
        }
    }
    async getMyBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBookings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBookings();
            return result;
        }
    }
    async getPricingRules(): Promise<PricingRules> {
        if (this.processError) {
            try {
                const result = await this.actor.getPricingRules();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPricingRules();
            return result;
        }
    }
    async getSlotSettings(): Promise<SlotSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSlotSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSlotSettings();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeeklyEarnings(arg0: bigint, arg1: bigint): Promise<EarningsReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyEarnings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyEarnings(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isOwnershipClaimable(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isOwnershipClaimable();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isOwnershipClaimable();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async unblockSlot(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockSlot(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockSlot(arg0, arg1);
            return result;
        }
    }
    async updatePricingRules(arg0: PricingRules): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePricingRules(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePricingRules(arg0);
            return result;
        }
    }
    async updateSlotSettings(arg0: SlotSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSlotSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSlotSettings(arg0);
            return result;
        }
    }
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
